#! /bin/sh

# Run sxhkd for keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

#[------------------------------]
#[       Virtual Desktops       ]
#[------------------------------]

bspc monitor DP-2 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8


#[----------------------------]
#[       Tiling Options       ]
#[----------------------------]

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_motion_interval          2


#[----------------------------]
#[       Border Colours       ]
#[----------------------------]

bspc config active_border_color \#0A0A0A
bspc config normal_border_color \#0A0A0A
bspc config focused_border_color \#BBBBBB

#[----------------------------]
#[       Theme Settings       ]
#[----------------------------]
gsettings set org.gnome.desktop.interface gtk-theme "MonoThemeDark" &
gsettings set org.gnome.desktop.interface cursor-theme "macOS-Monterey" &
gsettings set org.gnome.desktop.interface icon-theme "Vector-Maia-dark" &
xsetroot -cursor_name left_ptr &

#[-----------------------]
#[       Autostart       ]
#[-----------------------]

nitrogen --restore
picom &
xinput --set-prop 11 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 10 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 9 'libinput Accel Profile Enabled' 0, 1
discord &
spotify &
noisetorch &

polybar bsp-1 &
polybar bsp-2 &
